### ISSUE TITLE
[BE] 로그인 기능 

### ISSUE THREAD

**Issue by Donga1125** [codestates-seb/seb45_pre_001#15]
### 만들고자 하는 기능이 무엇인가요?
정해진 아이디로 로그인 가능한 기능

### 해당 기능을 구현하기 위해 할 일이 무엇인가요?
1. [x] 기반 기술 이해
2. [x] 어떤 방식의 로그인 구현할지 생각
3. [x] 구조설계
4. [x] API 명세 확인
5. [x] 구현
6. [x] 테스트
### 예상 작업 시간
4days

**Comment by yawning5** [comment]
Spring Security로 할 예정입니다.
