### ISSUE TITLE
[BE] 서버환경 구축

### ISSUE THREAD

**Issue by YongILTree1** [codestates-seb/seb45_pre_001#3]
### 만들고자 하는 기능이 무엇인가요?
AWS 서버 환경 구축 

### 해당 기능을 구현하기 위해 할 일이 무엇인가요?
1. [x] EC2 인스턴스 환경 세팅 
2. [x] 데이터 베이스 설정 
3. [x] 보안 및 액세스 관리 
4. [x] 배포 자동화 (CI/CD 파이프 라인 구성)
5. [x] 서버 환경 변수 설정

### 예상 작업 시간
4days

**Comment by Donga1125** [comment]
The overall deployment failed because too many individual instances failed deployment, too few healthy instances are available for deployment, or some instances in your deployment group are experiencing problems.  
위 에러로 자동 배포시 deploy작업에 실패했습니다.

**Comment by Donga1125** [comment]
작업 완료하였습니다.
